import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import { EnquiryForm } from "@/components/enquiry";
import Footer from "@/components/footer";
import { url } from "inspector";



//FONT SETUP BY NEXT
const inter = Inter({ subsets: ["latin"] });

//METADATA FOR THE LAYOUT FOLLOWING PAGES
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//ROOT LAYOUT FOR GENERAL SITE VISITORS
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="px-1 sm:px-[15%] bg-gradient-to-tr from-teal-300 to-green-500">
        <Header />
        <main>
          
        {children}
        <EnquiryForm />
        <Footer />
        </main>
      </body>
    </html>
  );
}


