import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import EnquiryForm from "@/components/enquiry";
import { Toaster } from "@/components/ui/toaster";
import Floaters from "@/components/floaters";

//FONT SETUP BY NEXT
const inter = Inter({ subsets: ["latin"] });

//METADATA FOR THE LAYOUT FOLLOWING PAGES
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bgGradient = {
  background: `hsl(168.23deg 100% 3.22%)`
}



//ROOT LAYOUT FOR GENERAL SITE VISITORS
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="px-1 sm:px-[15%]" style={bgGradient}>
      <Floaters/>
        <Header />
        
        <main> 
          {children}
          <Toaster/>
          
          <Footer />
          
        </main>
      </body>
    </html>
  );
}




